### ISSUE TITLE
Live Query support

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma1#1205]
**What feature are you missing?**

While not yet part of GraphQL specification, this is a tentative request for live query support: including defer, live and stream directives.

Reference:

- Apollo support - https://github.com/apollographql/apollo-server/blob/master/ROADMAP.md#support-for-defer-live-and-stream
- Subscriptions vs live queries - https://github.com/facebook/graphql/issues/284
- Relay Modern support - https://facebook.github.io/relay/docs/new-in-relay-modern.html#graphql-subscriptions-live-queries

**How could this feature look like in detail? Tradeoffs?**

```
  feed {
    stories {
      author { name }
      message
      likeCount @live
    }
  }
}
```

**Comment by kbrandwijk** [comment]
To be honest, Apollo has been very, very silent about it for over a year (that's how old the roadmap is). Same goes for the GraphQL spec. Relay Modern supports 'live queries' by setting a poll interval, and just executing the same query every time, which in all honesty, has nothing to do with the proposed workings of live queries (getting deltas pushed).

So with no movement on the client side, the spec side, and the server side, I'm afraid this isn't going anywhere any time soon.

**Comment by joshhopkins** [comment]
>To be honest, Apollo has been very, very silent about it for over a year (that's how old the roadmap is). Same goes for the GraphQL spec. 

It's not total radio silence: “Support for these is now possible with Apollo Link, which can accept multiple results from an…” — @jbaxleyiii https://dev-blog.apollodata.com/apollo-client-2-0-5c8d0affcec7

Apparently [Apollo Link](http://apollo-link-docs.netlify.com/docs/link/#standalone) use observables to support live queries.

>So with no movement on the client side, the spec side, and the server side, I'm afraid this isn't going anywhere any time soon.

If nothing else, here's a place for the Graphcool community to +1

**Comment by jasonkuhrt** [comment]
Talks:

* [GraphQL Live Queries - Stephen Wan @ GraphQL Europe 2018
](https://www.youtube.com/watch?v=g-asVW9JFPw)
* [GraphQL and Live Queries: Rodrigo Muñoz | POST/CON 2018
](https://www.youtube.com/watch?v=TUgYyWC22og)
* [Rodrigo Muñoz - GraphQL Live: Reactive Queries at Facebook
](https://www.youtube.com/watch?v=BSw05rJaCpA)

**Comment by mattferrin** [comment]
I think Prisma's database oriented conventions empower it to implement live queries. Apollo and Relay don't have structured database rules. All queries and subscriptions have a where input.

**Comment by mattferrin** [comment]
I think Prisma's database oriented conventions empower it to implement live queries. Apollo and Relay don't have structured database rules. All queries and subscriptions in Prisma have a where input. Basically, if you put the where and what (the what is the queried fields) of the query into a subscription, you could recompute the query everytime the subscription fires. Get fancier on the client, you could patch using the subscription instead of refetching. My point, it could be built directly atop subscriptions because Prisma's so structured.

My biggest issue with Prisma right now is that subscriptions seem to receive in other windows and other tabs. I want them to receive in the same client/tab that caused the mutation, so I can jerry rig my live queries client-side in the interim.

**Comment by robertherber** [comment]
This would help a lot!
