### ISSUE TITLE
Support filtering on aggregated values

### ISSUE THREAD

**Issue by sorenbs** [prisma/prisma1#1279]
Support filtering on values aggregated over related nodes.

These filters apply both on top level queries and relation fields.

This syntax is highly experimental. Please provide feedback about the syntax and other aggregation functions you might need. 

### Supported aggregate functions

- avg
- count
- min
- max
- sum

### Examples

```graphql
# students where friends older than 25 have an average age less than 50
allStudents(where: { friends_agg: { filter: { age_gt: 25 },  condition: { age_avg_lt: 50 } } })

# students whose friends combined are less than 100 years old
allStudents(where: { friends_agg: { condition: { age_sum_lt: 100 } })

# combination of above
allStudents(where: { friends_agg: { AND: [
  { filter: { age_gt: 25 },  condition: { age_avg_lt: 50 } }
  { condition: { age_sum_lt: 100 } }
]}})
```

### Considerations

We can probably support the same filters for scalar lists. See https://github.com/graphcool/framework/issues/1275

## Other related issues

- [ ] [Filter nodes based on related aggregations #110](https://github.com/prisma/prisma/issues/110#issuecomment-432889431)

**Comment by kbrandwijk** [comment]
I don't really understand how the examples relate to aggregations. Where are you actually querying the aggregation, or defining what fields to aggregate on? Also see https://github.com/graphcool/framework/issues/70#issuecomment-312384756 (part of an issue that should probably be closed because of this new proposal).

**Comment by sorenbs** [comment]
#70 is about returning aggregated values. This issue is about filtering on aggregated values. They are somewhat related, but certainly two separate features. I'll prepare a proposal for returning aggregated values later :-)

**Comment by kbrandwijk** [comment]
Thank you for explaining. However, I still don't see in your examples what aggregate your are actually filtering on...

**Comment by kbrandwijk** [comment]
Okay, thank you for explaining. Taking a second look at the examples, I now spot the aggregation fields.
One more suggestion: for aggregation, I think it makes sense to split the aggregation fields into objects. I mention this in every proposal, because a query like this is harder to construct based on a user search form, for example.

So it's rather have: `allStudents(filter: { friends_agg: { condition: { age: { sum: { lt: 100 } } } } })`
Although it's a lot more verbose, it's much, much easier to construct using variables:
```
query ($condition: FieldAggregationCondition) { 
  allStudents(filter: { friends_agg: { condition: { age: $condition } } }) 
}
```
```
query ($field: FieldAggregation) { 
  allStudents(filter: { friends_agg: { condition: { $field } } }) 
}
```

**Comment by marktani** [comment]
How does this tie into ordering by aggregation? 🙂

**Comment by sorenbs** [comment]
@kbrandwijk I have updated the proposed API to be much simpler.

We still use the combined `age_gt` fields. If you think this should be changed, please open a separate issue, as this should be consistent across all filters. Now is a good time to raise this as [1.0](https://github.com/graphcool/framework/issues/353) introduces breaking changes anyway.

@marktani it does not. Ordering is currently specified by an enum value. We should consider changing that to something more flexible that can support that use case.

**Comment by kbrandwijk** [comment]
@sorenbs https://github.com/graphcool/framework/issues/1313
