### ISSUE TITLE
Cloud Firestore Connector

### ISSUE THREAD

**Issue by jannone** [prisma/prisma1#1660]
For **feature requests**, please fill in the next sections:

**What feature are you missing?**

A Cloud Firestore connector (from Google Firebase)

**How could this feature look like in detail? Tradeoffs?**

I guess much the same way as other NoSQL connectors that are being planned

**Comment by prescottprue** [comment]
Something that may be worth noting is that Firebase now [supports calling Authenticating with limited privileges](https://firebase.google.com/docs/database/admin/start#authenticate-with-limited-privileges) (i.e. as a client/user) when calling initializeApp with `databaseAuthVariableOverride` like so:

```js
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://databaseName.firebaseio.com",
  databaseAuthVariableOverride: {
    uid: "my-service-worker"
  }
});
```

This should be helpful when trying to query as a client since we can pass along their UID.
