### ISSUE TITLE
CosmosDB connector

### ISSUE THREAD

**Issue by nicojdejong** [prisma/prisma1#1663]
CosmosDB is Microsofts new cloud database

It would be great to have a connector for this database

**Comment by sorenbs** [comment]
Thanks @nicojdejong 

Can you describe your particular use case? Are you already using Cosmos?

**Comment by nicojdejong** [comment]
Dear Soren,

No I am considering the techstack for a startup. A graph database will centrainly be part of it.
Database as a service makes sense – as well as the fact that we are Microsoft focusses and will have some credits to burn on buying CosmosDB.

I have a better feeling with GraphQL syntax and resources than going through one of the excisting connectors to CosmosDB.
I discardd the idea of using GraphQL until I saw your connector. ArangoDB though was in view. It seems a great solution.

So no. No implementation to be done at this time. I am sure though that either the community or Microsoft will bridge the gap….

Rgds,

Nico

**Comment by tedwardc** [comment]
Hi Soren,

I second the request for supporting Cosmos Db.  I too am working on a startup and would love to be able to use Cosmos Db as the data store for a GraphQL API.  I chose Cosmos Db because I work with really large data sets (one is >250 GB) and they offer auto-indexing and fast response times.

I was beginning to think I needed to write a connector myself but I would much rather work on value-added features and not so much on plumbing if I could.

I've been running with Apollo-* stack and haven't seriously considered Graphcool because of this limitation but I would love to just leverage all the magic you guys have created and not worry about it :)

Best,
Ed

**Comment by benmccallum** [comment]
+1

**Comment by infin8loop** [comment]
+1 We are making a foray into Cosmos DB after starting out with graphcool.  Lack of other database support is probably our biggest hurdle for Prisma (i.e. we want MS SQL, Cosmos DB or Postgres).

**Comment by sorenbs** [comment]
Thank you all!

We have finished the ground work required to support more database connectors. The implementation of Postgress is set to start next week and more will follow soon after. I can't offer a concrete timeline for Cosmos DB yet though.

**Comment by kevineger** [comment]
@sorenbs great news! Any update on a Cosmos DB roadmap? I'd potentially be interested in contributing.

**Comment by AronT-TLV** [comment]
Has anyone tested the MongoDb connecter with CosmosDB - it supports the Mongo wire do in principle it should work

**Comment by AronT-TLV** [comment]
Thanks @stilren

**Comment by trumhemcut** [comment]
+1

**Comment by LexSwed** [comment]
Just a heads up? Any updates on that?
