### ISSUE TITLE
PostGIS support

### ISSUE THREAD

**Issue by joshhopkins** [prisma/prisma1#1760]
PostGIS is a very popular extension for Postgres. Please consider supporting this when designing the new Postgres API.

https://postgis.net

**Comment by sorenbs** [comment]
The PostgreSQL connector issue is https://github.com/graphcool/prisma/issues/1641. Let's keep this issue to discuss PostGIS support :-)

**Comment by joshhopkins** [comment]
Should remain open, thanks Probot.

**Comment by zuohuadong** [comment]
+1

**Comment by lcalisto** [comment]
+1

**Comment by haysclark** [comment]
+1

**Comment by ontwikkelfabriek** [comment]
PostGIS support asp please

**Comment by rilexus** [comment]
+1

**Comment by NormalAndrew** [comment]
+1

**Comment by yagoferrer** [comment]
+1 Please we need support for PostGIS.

**Comment by bnolan** [comment]
PostGIS support would be great.

**Comment by Fi1osof** [comment]
+1

**Comment by sagswe** [comment]
+1

**Comment by wmurmann** [comment]
+1

**Comment by jebenois** [comment]
+1

**Comment by piemonte** [comment]
for anyone interested, i think this issue is old and part of prisma1 which is in "maintenance mode".

i found these issues for prisma2, which seems like they're getting closer to adding some support:

📎 https://github.com/prisma/prisma/issues/2789
📎 https://github.com/prisma/prisma/issues/1798
📎 https://github.com/prisma/prisma/issues/3447

**Comment by jebenois** [comment]
+1

**Comment by glenmcrae** [comment]
Really looking forward to this! +1

**Comment by jebenois** [comment]
+1

**Comment by francescortiz** [comment]
We are not using prisma because of this. So +∞

**Comment by frimmy** [comment]
@francescortiz what did you guys decide to roll with instead? 👀

**Comment by francescortiz** [comment]
We went for MikroORM, because we can use `@Formula` for custom values: https://mikro-orm.io/docs/defining-entities#formulas. Also, being able to manually extend the models (entities) is a nice feature.

Moreover, if we need to extend it, we don't have a proficient team in rust by now, so we would have been completely dependent on you.

But the experience with prisma was awesome! I would have loved to stay with it. Specially because of the beauty with which cursors are handled.

**Comment by nk9** [comment]
Looks like I'll have to try a different ORM for my Next.js mapping project. So +1 from me.
