### ISSUE TITLE
Fire subscription events for batch mutations

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2327]
# Feature Request

**What feature are you missing?**

Currently, [batch mutations](https://www.prisma.io/docs/reference/prisma-api/mutations-ol0yuoz6go#batch-mutations) don't fire subscription events.

**How could this feature look like in detail? Tradeoffs?**

Firing subscription events for batch mutations is potentially expensive, and might not always be desired. Therefore, this behaviour could be controlled by a third input argument `subscriptions`:

```graphql
mutation {
  updateManyPosts(
    where: {
      isPublished: false
    }
    data: {
      published: true
    }
    subscriptions: {
      fire: true
    }
  ) {
    count
  }
}
```

**Comment by shufflingB** [comment]
Hi,

Apologies if this is mentioned elsewhere, but I wonder if a similar option might be useful for vanilla deletes in order to ensure that the model onDelete CASCADE feature can be used effectively in conjunction with subscriptions?

For instance, the model below models parent-child relationship links.  onDelete CASCADE is useful because it enables the atomic removal of all of an Item's redundant parent-child Link nodes when the Item is deleted which improves the reliability of the data hygiene process. 

Meanwhile, without the onDelete CASCADE, subscribing to changes on the Link is also good way to pick up all incremental create, delete and update operations that might effect a UI's display. 

Seems a bit of a shame not be able to use both together because the subscription doesn't pick up the deletes.

```
type Item @model {
    id: ID! @unique
    childLinks: [Links!]! @relation(name: "ParentToLink", onDelete: CASCADE)
    parentLinks: [Links!]! @relation(name: "ChildToLink",onDelete: CASCADE)
}
type Link @model {
    id: ID! @unique
    rank: Int
    parentItem: Item! @relation(name: "ParentToLink", onDelete: SET_NULL)
    childItem: Item! @relation(name: "ChildToLink", onDelete: SET_NULL)
}
```

**Comment by murdockq** [comment]
I am currently running into performance issues with repeated query/update loops to make updates for a notification system that is connected to client subscriptions.  Any progress on getting this scheduled for a release version?
