### ISSUE TITLE
CLI should offer a hint to remove @rename after Deploy

### ISSUE THREAD

**Issue by do4gr** [prisma/prisma1#2373]
The @rename directives are causing errors when a user forgets to remove them. 

The CLI should detect them and remind users to remove @rename on models and fields and the oldName subfield of relation directives.

Thanks at @cameronk

**Comment by mzygmunt** [comment]
I think that the  @rename clausule should be ignored (or only throw warning) after correctly renaming field in db.

**Comment by frankdugan3** [comment]
A further thought: This causes a lot of friction when iterating in development, then pushing to CI. Because it errors out after running it once, I need to constantly add, remove, then remember to add back `@rename` before committing. Makes it easy to break a CI deploy.

Especially in the case where Prisma is being used in software that end users deploy in-house, it makes much more sense for `@rename` to stick around for users that may skip a few releases.

I like the aforementioned idea of a simple warning.
