### ISSUE TITLE
Google Cloud Spanner database connector

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [prisma/prisma1#2650]
This feature request serves as a central place to discuss development and progress for the Google Cloud Spanner database (https://cloud.google.com/spanner/) connector.

**Comment by janat08** [comment]
whats stopping this from working now?

**Comment by jhalborg** [comment]
I haven't tried, just researching, but [](url) says:

> Spanner is a distributed data layer that uses optimized sharded Paxos to guarantee consistency even in a system that spans multiple geographic regions. Only it's query API is SQL (i.e. selects) its insert and updates are done through a specialised grpc interface. So you need to rewrite parts of you application to support it.

So I'm guessing a specific connector is needed because write syntax is different

**Comment by jhalborg** [comment]
Update! 

Google Cloud Spanner recently introduced `INSERT`, `UPDATE`, and `DELETE` as direct DML! There are two caveats, though.

1. In the docs [under "locking" and "concurrency"](https://cloud.google.com/spanner/docs/dml-tasks), it says:

> Locking
You execute DML statements inside read-write transactions. Cloud Spanner acquires shared read locks on all rows that it reads, including rows that might not match the filter condition of the WHERE clause. Cloud Spanner acquires exclusive locks on rows that it modifies. The result is that Cloud Spanner might lock a large number of row ranges or an entire table, even if the transaction only modifies a few of the rows it reads. To lock fewer rows, scope the WHERE clause for UPDATE and DELETE statements to small primary key ranges by including the primary key columns in the WHERE clause.

Concurrency
Cloud Spanner sequentially executes all the SQL statements (SELECT, INSERT, UPDATE, and DELETE) within a transaction. They are not executed concurrently. The only exception is that Cloud Spanner might execute multiple SELECT statements concurrently, because they are read-only operations.

I'm not sure how well that plays with Prisma?

2. I'm also not sure if Prisma needs [partitioned DML](https://cloud.google.com/spanner/docs/dml-partitioned) to work?

Some input from the Prisma team on this would be nice. If their assessment is that it should now work, I volunteer to create a Google account and set up an environment with my app and test it, but I'd rather not waste time on it if I overlooked something the Prisma team knows :-)

**Comment by jhalborg** [comment]
It'd be great with some input from @marktani , or perhaps you can direct the question to someone else on the team?

**Comment by allwApps** [comment]
Prisma 2 came out , any news about cloud spanner support ?

**Comment by cullylarson** [comment]
I'm interested in investigating if this might be possible. Is a "connector" an abstraction Prisma makes? Looking through the code, I don't see any abstraction on the provider specifically; everything is just mixed together. I don't see a way to add something like Cloud Spanner without updating Prisma itself.

**Comment by wgottschalk** [comment]
I'd love to see Spanner supported. Now that Spanner has [granular instance sizing]( https://cloud.google.com/blog/products/databases/get-more-out-of-spanner-with-granular-instance-sizing) and cloud sql has mandatory downtime where Spanner doesn't, it makes it the preferred database over cloudsql.

**Comment by wgottschalk** [comment]
Update here: Spanner is starting to rollout a postgres dialect to spanner. They mention it's not 100% compatible but it would be great have prisma add some documentation outlining limitations if any 

https://cloud.google.com/spanner/docs/postgresql-interface
