### ISSUE TITLE
Don't mark fields as updated if value didn't change in subscriptions

### ISSUE THREAD

**Issue by marktani** [prisma/prisma1#2654]
**Is your feature request related to a problem? Please describe.**
When updating a node without actually changing the fields, update subscriptions are triggered, and the `updatedFields` variable contains fields.

Example

subscription:

```
subscription {
  user(where: {
    mutation_in: [CREATED, UPDATED, DELETED]
    node: {
      id: "cjilqw49tzlp30a86h5to2ogj"
    }
  }) {
    node {
      id
      name
    }
    updatedFields
  }
}
```

mutations

```
mutation a {
	createUser(data: {
    name: "Nilan"
  }) {
    id
  }
}

mutation b {
	updateUser(
    data: {
      name: "Nilan"
    }
    where: {
      id: "cjilqw49tzlp30a86h5to2ogj"
    }
  ) {
    id
  }
}
```

after mutation `b`, the subscription will trigger this event:

```
{
  "data": {
    "user": {
      "node": {
        "id": "cjilqw49tzlp30a86h5to2ogj",
        "name": "Nilan"
      },
      "updatedFields": [
        "name"
      ]
    }
  }
}
```

**Describe the solution you'd like**

Subscription events should not be triggered if no field of a node changed.

**Describe alternatives you've considered**
An alternative is to add a flag to the subscription filter to let the user decide whether or not those subscriptions should be fired.

**Additional context**
Initial [Forum discussion](https://www.prisma.io/forum/t/new-feature-requests-for-subscriptions/3425?u=nilan).

**Comment by agonbina** [comment]
Naturally I would also expect this to be the default behavior without having to do additional filtering at the subscription level. 
Hopefully this will become the default behavior once this issue is considered.

**Comment by ItsWendell** [comment]
I totally agree, a thing that I have to do manually within my mutations is to check if DateTime fields are updated (since the input string might differ from the actual iso string from the database, for example they might include timezones that prisma automagically takes care of), in order to not trigger any field updates on those fields. 

Also when no fields changed at all, the UPDATED subscription still gets called when upserting data, i.e.

```
...
"mutation": "UPDATED",
"updatedFields": [],
...
```

I think this causes me to unnessesarly write a lot of extra logic in order to not trigger the mutations (in my query, and in my resolvers to check for DateTime value changes).
