### ISSUE TITLE
Add support for more PubSub systems

### ISSUE THREAD

**Issue by mavilein** [prisma/prisma1#2867]
**Is your feature request related to a problem? Please describe.**
In the [issue](https://github.com/prismagraphql/prisma/issues/2850) on horizontal scaling it became apparent that our community would like to see support for other PubSub systems than RabbitMQ.

**Describe the solution you'd like**
We should add support for more PubSub systems. This should probably be configurable through the Prisma server config.

**Describe alternatives you've considered**
People do not really like the additional dependency for a PubSub. We need it for those reasons:

1. to power subscriptions over Websockets
1. to store ServerSideSubscriptions/Webhooks in a Queue. This allows us to eventually deliver Webhooks even if the Server goes down due a crash or reboot.
1. to propagate information about schema changes to all servers. We need this as each server holds a cache of the schema of service. Not having a cache would mean adding significant latency to query execution.

Many people are probably fine with not having support for point 1 and 2. So we could come up with an alternative solution for 3 that could involve polling or a database level pubsub.

**Comment by goulderb** [comment]
My team uses Kafka as an integral part of our stack already, and I would vote for having Kafka as a pubsub option so that we could directly subscribe to messages from Prisma rather than our current solution (which is basically using the WebSocket subscriptions to then push things into Kafka for the rest of our system to consume).

**Comment by mavilein** [comment]
@goulderb : Sounds good to me. We are looking into Kafka for other features anyway. As a temporary workaround i would suggest using our Server Side Subscriptions aka Webhooks that support the same subscription queries. That is probably easier to use than the Websockets.

**Comment by goulderb** [comment]
@mavilein Thanks for the suggestion. I will definitely look into using server side subscriptions.

**Comment by mcmar** [comment]
Any of the systems that AmazonMQ supports.
JMS, NMS, AMQP (1.0, not 0.9), STOMP, MQTT

**Comment by develomark** [comment]
Google PubSub would be useful also for horizontal scaling if your Prisma servers are in GCP. GCP PubSub is infinitely globally scalable and far simpler to implement and support over spinning up an additional PubSub server to support messaging.

**Comment by frandiox** [comment]
`graphql-subscriptions` supports a bunch of PubSub implementations. It would be nice to see some of them in Prisma in order to use the same infrastructure we already have for the app servers: https://github.com/apollographql/graphql-subscriptions#pubsub-implementations
Perhaps if the PubSub API part of Prisma server is documented and refactored as necessary, these PubSub implementations could be made by the community just like in `graphql-subscriptions`.

That said, I also vote for Google PubSub 👍

**Comment by j4jefferson** [comment]
I am currently trying to deploy graphql-yoga/prisma backend to GCP Kubernetes cluster and hooked up to CloudSQL Postgres and finding it very hard to figure out. Having got the app node and prisma node successfully deployed with a custom prisma image packing cloud_sql_proxy I then tried to connect to prisma cloud and failed. That's when I discovered this issue of the management api and pubsub. Getting prisma to production ain't easy folks! I definitely want to cast a vote for GCP pubsub for primary/secondary sync as well as subscriptions.
