### ISSUE TITLE
Security Precautions

### ISSUE THREAD

**Issue by heymartinadams** [prisma/prisma1#2880]
**Is your feature request related to a problem? Please describe.**
Security is obviously of prime importance, and I’m exploring various potential security loopholes prior to release of our Prisma Cloud-based SaaS. This [excellent essay](https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b) by @mxstbr opened my eyes to some of the potential issues we’d need to be ready for.

**Describe the solution you'd like**
Thus far I’m not seeing any of these issues addressed in the [new Prisma Docs](https://docs-beta.prisma.io/) — for example, how to implement rate limitation, depth limitation, and query cost analysis. Is that because it’s not really within Prisma’s scope to offer these services or docs, or is it something that will be explained and implemented in the future?

**Comment by nikolasburk** [comment]
Hey @heymartinadams, thanks a lot for brining this  up! Topics like rate limiting and depth limitation are indeed not really in the scope of Prisma as they're typically implemented in _public facing_ APIs which is not how Prisma is intended to be used. So these mechanisms need to be implemented on the _application layer_ rather than the Prisma layer. 

In any case, we're planning to add new `Best practices` section to our new docs soon! We'll cover these topics there, I'm leaving this issue open until then!

**Comment by heymartinadams** [comment]
Here’s another great security resource (adding this to the discussion for reference): https://graphqlmastery.com/blog/graphql-security-in-node-js-project

**Comment by heymartinadams** [comment]
Hey bot, I’d still be interested in a `Best practices` section ☺️

**Comment by heymartinadams** [comment]
Perhaps we should keep it open, @nikolasburk?

**Comment by heymartinadams** [comment]
Bot... keep it open, please.

**Comment by pantharshit00** [comment]
Added the feature label so that bot doesn't mark this as stale.
