### ISSUE TITLE
Prisma generated queries and subscriptions have lowercase first letter for all-caps type name.

### ISSUE THREAD

**Issue by liamdanielduffy** [prisma/prisma1#2996]
**Describe the bug**
I have a type called RSVP in my prisma datamodel.graphql. 

After deploying the service, I get the following queries and subscriptions:

`rSVP(...)`  (query / subscription)
`rSVPs(...)`
`rSVPsConnection(...)`

**To Reproduce**
1. Create a prisma service with an all-caps type
2. Deploy the service
3. See generated prisma queries and subscriptions

**Expected behavior**
I would expect the queries and subscriptions to preserve the capitalization of the type, like this:

`RSVP(...)`  (query / subscription)
`RSVPs(...)`
`RSVPsConnection(...)`

**Screenshots**

**Versions (please complete the following information):**
 - OS:  `OS X High Sierra`
 - `prisma` CLI: `prisma/1.12.0 (darwin-x64) node-v8.11.1`
 - Prisma Server: `1.11-beta`
 - Prisma bindings: `2.1.1`

**Comment by liamdanielduffy** [comment]
@marktani Understood. I guess this is more of a feature request / request for a design change.

To me, it feels counterintuitive to query the type `RSVP` with the query `rSVP`.

It breaks the general pattern of just typing the `<typename>` to query for a single node, or `<typename>s` to query for multiple nodes.

Instead, the pattern now has an added case for any all-caps `<TYPENAME>`, where the first letter must be lowercase. 

It feels more intuitive to me to keep the general pattern regardless of capitalization.

**Comment by mcmar** [comment]
I've also run into this and I personally renamed my class to align better with the Prisma standards. What I've found is that you should only capitalize the first letter of any acronym.
So instead of `DVDPlayer`, I would do `DvdPlayer`.

This is also considered best practice in Java due to the same issue of `PascalCase` vs `camelCase`. So in Java, you would do:
```
User user = new User();
Rsvp rsvp = new Rsvp();
HttpUrlConnection httpUrlConnection = new HttpUrlConnection();
```

I choose to follow the same conventions for Prisma and so I renamed `DMChannel` to `DmChannel`

**Comment by mcmar** [comment]
But also maybe a suggestion for @marktani , we could probably add a directive for naming to models. This could also include pluralization for those rare edge cases where a super pedantic person wants to query `octopi` instead of `octopuses` or `yehudim` instead of `yehudis` or `attorneysGeneral` instead of `attorneyGenerals`.
