### ISSUE TITLE
Client generated API and GraphQL API differences

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#3185]
**Is your feature request related to a problem? Please describe.**
The generated client and the underlying Prisma GraphQL API are not a 1-1 mapping. The client attempts to simplify some cases enabling users to write less code for a few operations. 

**Typescript Client**

1. Create mutations

GraphQL
```
mutation ($data: TodoCreateInput!) {
  createTodo(data: $data) {
    id
    title
    createdAt
  }
}
```

Client
```
await prisma.createTodo({
  title,
})
```

Notice that client simplifies it by removing the `data` wrapper. 

2. Delete mutations

GraphQL
```
mutation ($where: TodoWhereUniqueInput!) {
  deleteTodo(where: $where) {
    id
    title
    createdAt
  }
}
```

Client
```
await prisma.deleteTodo({
  title,
})
```

Notice that client simplifies it by removing the `where` wrapper.

3. Queries with only one argument which is `where`

Similarly to the above two examples, Prisma client simplifies the API by removing the singular variable wrapper. 

4. `$raw` and `executeRaw`

Prisma GraphQL API exposes a special mutation called `executeRaw`. The client does not expose the `executeRaw` mutation and instead exposes the functionality on `client.$raw` namespace. 

**Go Client**

1. Go Client `nil` type safety does not match 1-1 with GraphQL schema. Here is the relevant discussion: https://github.com/prisma/prisma/issues/3288

**Describe the solution you'd like**
While the new shorter API is convenient to use and does the same thing with less code. It deviating from the underlying GraphQL might cause some confusion. Particularly, in JS only codebases when usually there would be no autocompletion etc. Also, when we fall back to raw GraphQL for a task, the deviation from the GraphQL API might lead to confusion. 

This issue tracks the discussion around this topic and we want community feedback on how beneficial this deviation is and if we need to make amends to it.

**Comment by simonjoom** [comment]
hello 
I tried prisma-client one thing about this 'writelesscode' 
Yes indeed was a good point but for me gave me some headache more than supposed to resolve;
Before with prisma-binding we used forwardTo who is great because args are consistent between the layers.

I explain why here in resolver:

just about the where thing:

if i query user from dashboard
args= { where: { id: userId } }

but i have to add some line of code 
to transform it in 
args={id: userId} 
 to query with prisma client.

with forward in resolver just 
User: forwardTo('db'),
is convenient because args are the same. It's just avoid lot of headache i think.

So yes writelesscode maybe is not a good feature. just one where property is not so much i think

**Comment by psycura** [comment]
@simonjoom , i agree with you - the `forwardTo` its a great feature, but you can use them both prisma client and the prisma-bindings,
jus pass to the server both of them:
```
return new GraphQLServer ( {
        typeDefs:                  'src/schema.graphql',
        resolvers:                 { Mutation, Query },
        resolverValidationOptions: {
            requireResolversForResolveType: false
        },
        context:                   req => ({ ...req, prisma, db })
    } )
```
and in the mutations and queries you can use both functionality
