### ISSUE TITLE
Prisma client - generate enum types

### ISSUE THREAD

**Issue by maxprilutskiy** [prisma/prisma1#3429]
**Is your feature request related to a problem? Please describe.**
Prisma client should take advantage of TypeScript's `enum`s instead of just using `type`

**Describe the solution you'd like**
I would like to make codegen module generate TypeScript `enum`s from GraphQL's enums, instead of `type`s.

Advantages:
1. More obvious;
2. Utilizes TypeScript language features;
3. Improves compatibility with other libraries related to code generation.

**Comment by prilutskiy** [comment]
I am going to submit a PR with this change

**Comment by schickling** [comment]
Thanks a lot for opening this issue and suggesting this change. This is a little bit tricky since the `enum` TS syntax and the currently supported string literal syntax are not compatible (this is by design - [see this Github issue](https://github.com/Microsoft/TypeScript/issues/17690)).

Your proposed change would result in a breaking change which would in most cases require a more explicit syntax. Consider the following example based on the giving `datamodel.prisma` snippet:

Datamodel:

```graphql
enum Color { Red, Blue }
```

Resulting TS client types using literal string syntax (current implementation):

```ts
type Color = 'Red' | 'Blue'

// allows for the following
const c1 = 'Red' // ok
const c2 = 'Green' // compile error
```

Resulting TS client types using enum syntax (your suggestion):

```ts
enum Color {
  Red: 'Red',
  Blue: 'Blue'
}

// allows for the following
const c1 = 'Red' // compile error
const c2 = 'Green' // compile error
const c3 = Color.Red // ok
```

---

There is however a workaround described [in the comments of the mentioned issue](https://github.com/Microsoft/TypeScript/issues/17690#issuecomment-350863594) which would allow both the `'Red'` and the `Color.Red` syntax. See the following:

```ts
export type Color = 'Red' | 'Blue'
export const Color: {
  Red: 'Red',
  Blue: 'Blue',
} = {
  Red: 'Red',
  Blue: 'Blue',
}

// allows for the following
const c1 = 'Red' // ok
const c2 = 'Green' // compile error
const c3 = Color.Red // ok
```

While my suggested workaround wouldn't use the canonical `enum` syntax you've described, it would still allow for both referencing syntaxes. Does this solve your requirements?

**Comment by VRspace4** [comment]
Any progress on this? The difference in the way Prisma generates the enum (`string unions`) versus my GraphQL client's way (`typescript enum`) causes conflicts in the types.

**Comment by chrisui** [comment]
I would like to throw weight behind switching to canonical `enum` syntax here. I personally only see the explicitness as a positive especially since enum values should ideally be seen as opaque. This change would also help the generated types follow a favourite [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)! :)

**Comment by WaqasAliAbbasi** [comment]
I fixed the incompatibility between GraphQL Code Generator enums and prisma client enums by setting `enumAsTypes:true` in codegen.yml. See [here](https://graphql-code-generator.com/docs/plugins/typescript#enumsastypes-boolean-default-value-false) for more details.

**Comment by WaqasAliAbbasi** [comment]
> Any progress on this? The difference in the way Prisma generates the enum (`string unions`) versus my GraphQL client's way (`typescript enum`) causes conflicts in the types.

I fixed the incompatibility between GraphQL Code Generator enums and prisma client enums by setting `enumAsTypes:true` in codegen.yml. See [here](https://graphql-code-generator.com/docs/plugins/typescript#enumsastypes-boolean-default-value-false) for more details.

**Comment by sarink** [comment]
Why is this not getting more attention? The point of declaring an enum is to... have an enum

**Comment by cqh963852** [comment]
```
export type Color = 'Red' | 'Blue'
export const Color: {
  Red: 'Red',
  Blue: 'Blue',
} = {
  Red: 'Red',
  Blue: 'Blue',
}

// allows for the following
const c1 = 'Red' // ok
const c2 = 'Green' // compile error
const c3 = Color.Red // ok
```
I meet a problem in this way.

My project is base on nextjs.
I import `Color` in a function, and the function is used in react component.Then there comes webpack error. 

Because the frontend code is importing prisma generated js file.

If the enum is just typescript enum. It won't happend.
```
export enum Color: {
  Red = 'Red',
  Blue = 'Blue',
}

// allows for the following
const c1 = 'Red' // ok
const c2 = 'Green' // compile error
const c3 = Color.Red // ok
```
