### ISSUE TITLE
Implement alias-based query batching in Prisma client

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#3599]
Prisma client has a built-in [dataloader](https://github.com/facebook/dataloader) to ensure multiple resolver invocations are getting batched when sent to the Prisma API.

It currently uses the [network-level Apollo batching](https://www.apollographql.com/docs/react/advanced/network-layer.html#query-batching) which takes all generated Prisma client queries and puts them into the same HTTP request - however, these queries are still represented as _individual query documents_. Therefore, the Prisma _server_ treats each query as a single HTTP request and generates one database query per query that was originally submitted by the Prisma client.

This can be solved by using a different batching strategy. Instead of using Apollo network-level batching, the client should use a batching API that adds all queries to the same query document. That way the Prisma server will be able to generate a single database query to resolve all initial data requirements. 

This new batching strategy needs to support aliases to enable using the same root query multiple times inside the same query document.

**Comment by P4sca1** [comment]
Would be great if the prisma client could automatically batch and cache on a per incoming graphql request level.

What I mean by that is when you set up your own apollo server and you use prisma inside the resolvers it would be great if all prisma requests that belong to the one graphql request are batched / cached together.

For this to work the prisma client would need to have a seperate dataloader for every request.
Currently we do this to access prisma from within the graphql context:
```ts
new ApolloServer({
  context: () => { prisma }
})
```

For the caching to work we could use something like this:
```ts
new ApolloServer({
  context: () => { prisma: prisma.dataloader() }
})
```

The `prisma.dataloader()` method would return a prisma instance wrapped into a dataloader instance.

I don’t know if it could work exactly like that (the most critical part will be to wrap the prisma client into a dataloader I guess), but it could improve performance drastically without requiring any change of code in the resolvers.

**Comment by P4sca1** [comment]
With ORMs like TypeORM, we have access to the relation ids in a one-to-one or many-to-one relation, which makes it relatively easy to implement the dataloader pattern, because you know the ids of the objects you are fetching. This is not the case with prisma. This spectrum discussion shows that it is not really possible to implement the dataloader pattern for caching: https://www.prisma.io/forum/t/prisma-how-to-cache-repetitive-queries/4588
However, because it can drastically improve performance, it would be great if something similar would be supported.
Could you clarify whether the plan for this issue is to also support caching on the client? Could that even work without knowing the relation ids before?

**Comment by pantharshit00** [comment]
@P4sca1 Please see https://github.com/prisma/rfcs/blob/new-ts-client-rfc/text/0000-new-ts-client.md. Maybe comment on the RFC about this

**Comment by biels** [comment]
Any updates? Imo, this is an essential feature to be able to build graphql servers based on prisma that are reasonably performant. What's the point of using prisma if you still have to implement the dataloader everywhere by yourself?
