### ISSUE TITLE
Cannot update relations in updateMany mutations

### ISSUE THREAD

**Issue by sapkra** [prisma/prisma1#3602]
**Describe the bug**
The problem is that I cannot disconnect relations when I try to use e.g. `updateManyUsers` because all values with relations are missing in `UserUpdateManyMutationInput`.
Everything works fine when I use `updateUser` because all values are available for `UserUpdateInput`.

**To Reproduce**
Should be reproducible by just adding a relation to a model in `datamodel.prisma` and generate a new prisma-client.

**Versions (please complete the following information):**
 - OS: `OS X High Sierra`
 - `prisma` CLI: `prisma/1.21.1 (darwin-x64) node-v8.12.0`
 - Prisma Server:`1.21.1`

**Comment by delianides** [comment]
This should probably be renamed because in addition to disconnect you can't `create` or `update` either. 

These methods do work in `prisma-bindings`

**Comment by pantharshit00** [comment]
Hi,

We currently do not allow non-unique values in updateManyInput. Maybe this is something we can add in the future so I am marking this as a feature request. Currently, you can grab all user ids and use the update method instead.

@delianides I think it is also not possible in binding as well because bindings just delegate queries to prisma server and this is currently not possible there. If this is possible can you provide us with the example 🙂? You can certainly do this by grabbing ids in previously but I don't think so you can do this in one single command.

**Comment by vjsingh** [comment]
Is this still not possible? Seems like it would be useful.

**Comment by sapkra** [comment]
Maybe it's already possible in prisma2 but I've not tried it yet.
