### ISSUE TITLE
More than two consecutive uppercase characters in type name breaks GoLang generated client

### ISSUE THREAD

**Issue by asilluron** [prisma/prisma1#3646]
**Describe the bug**
More than two consecutive uppercase characters in type name breaks the logic used to create the "auxiliary types". 

**To Reproduce**
If I name a type `ABCType`, it will produce the following code:

```
func (instance *ABCTypeSubscriptionPayloadExec) Node() *AbcTypeExec {
```

However, `AbcTypeExec` is _actually_ defined as
```
type ABCTypeExec struct {
	exec *prisma.Exec
}
```

produces error 

>  undefined: AbcTypeExec

**Expected behavior**
To compile without errors

**Versions (please complete the following information):**
 - `OS X High Sierra`
 - `prisma` CLI:  1.20.7
 - Prisma Server: 1.19.3 and 1.20.7

**Comment by dominikh** [comment]
The mismatch between type names is even greater than that. For ABCType, we get a method `ABcType`, and the types `AbcTypeExec` and `ABCTypeWhereUniqueInput`. We really covered all ways of spelling it. 

Working on it.

**Comment by dominikh** [comment]
Can someone confirm what the other language generators (such as JS) generate in terms of field names? The "ABc" spelling is caused by an underlying field name of "aBC" (`field.name` in https://github.com/prisma/prisma/blob/875eb6cb99fd5c975fa25d43caede914b2bf7a17/cli/packages/prisma-client-lib/src/codegen/go-client.ts#L471). I suspect the generator framework just takes the type name and lowercases the first letter?

**Comment by timsuchanek** [comment]
@dominikh in javascript the field names are not changed. That means if we have an API like this:
```ts
client.user().myFieldName()
```
We're not uppercasing the field name.
Are we uppercasing the field names in Go due to Go conventions?

**Comment by dominikh** [comment]
> We're not uppercasing the field name

No, but the type name has its first character lowercased in the generated GraphQL schema. Given a type `ABCType` in the data model, the following GraphQL query type gets generated:

```
type Query {
  aBCType(where: ABCTypeWhereUniqueInput!): ABCType
  aBCTypes(where: ABCTypeWhereInput, orderBy: ABCTypeOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [ABCType]!
  aBCTypesConnection(where: ABCTypeWhereInput, orderBy: ABCTypeOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): ABCTypeConnection!
  node(id: ID!): Node
}
```

That is, the first letter of methods is lowercased.

The issue is that the Go generator, in turn, is given that lowercased name. Even if we did nothing to the name, it would clearly be wrong.

And yes, we do have to uppercase the name in Go because only identifiers that start with a capital letter are exported. We're also trying to turn snake_case identifiers into CamelCase, so that `foo_bar` becomes `FooBar`. I will experiment with unconditionally uppercasing the first letter and see if that works with all the edge cases.

Independent of the Go issue, you may want to analyse whether the generated GraphQL schema warrants fixing.

**Comment by mauriyouth-tcmlabs** [comment]
Seems also that long field as `Subscription` fails with SubscriptionExec `undefined`
