### ISSUE TITLE
Docs: Deploy new datamodel with rolling deployment

### ISSUE THREAD

**Issue by sapkra** [prisma/prisma1#3789]
Hey guys, I have something what is missing in the docs related to a rolling deployment on kubernetes:

When I deploy my graphql server (prisma client) with a rolling deployment they should only be connected to a compatible prisma server.

How can I solve this when I have to deploy a new datamodel?
It would be great to have this case documented.

**Comment by SergeiMeza** [comment]
The data model deployment lives on the database and not in the Prisma server.

**Comment by serendipity1004** [comment]
@SergeiMeza I think what @sapkra is trying to say is that when prisma server settings change in kubernetes script and is deployed through ci/cd, say travis, then there is a bit of downtime on the prisma server until new script deploys prisma server with new settings. Since `prisma deploy` requires prisma server to be ready, it will not work until rolling update is done. What @SergeiMeza is saying is great since pods in kubernetes is not guaranteed to stay up forever so when new pod comes in it will look in the DB to import settings from previous pod; however, when rolling update and schema deployment has to be done at the same time(automated), it is quite difficult to achieve at the moment.
