### ISSUE TITLE
Whats difference between create and update for embedded type

### ISSUE THREAD

**Issue by playerx** [prisma/prisma1#3797]
I think there is no need to have `create`, `update`, `upsert` for embedded types. create and update do the same thing as I've tested and there can be just one of them, or just `save`

**Comment by do4gr** [comment]
In some cases the effect of `create`, `update` and `upsert` can be the same, that is true. 

But when it comes to toMany relations they start to differ since there can be multiple embedded documents connected via the same relation. 

Also the user might want to change only one value using the `update`, instead of using `save` where he would presumably have to provide all the previous values.
