### ISSUE TITLE
Problems work with the renamed field when using graphql-shield

### ISSUE THREAD

**Issue by baby1990** [prisma/prisma1#3881]
When I use graphql-prisma / graphql-yoga / graphql-shield together to perform a backend service, the renamed field not work. But when I just use graphql-yoga and graphql-shield with static data, it works.

The test demo repository： [url](https://github.com/baby1990/test-graphql-shield)

When I add rules to a relation field such as posts, sometimes I maybe want to get the posts published or not-published in one query. Just like this:
```
query {
  user(id: "cjqvom8dt0014088577nx1li9") {
    id
    postsNotPublished: posts(where: {publish: false}) {
        id
        publish
    }
    posts(where: {publish: true}) {
        id
        publish
    }
  }
}
```
But after use graphql-shield middleware, add some rules(like isAuthenticated) to the ``posts`` field of type ``User``, the result of the query above is not worked correctly. The renamed field ``postsNotPublished``
cannot work through the validation of the ``posts`` field.
The value of ``postsNotPublished`` field is just the same of ``posts`` above:
```
{
  "data": {
    "user": {
      "id": "cjqvom8dt0014088577nx1li9",
      "postsNotPublished": [
        {
          "id": "cjoy6mxbm011k0759uaito9hs",
          "publish": true
        },
        {
          "id": "cjoy3qcsj010807595jbtqt35",
          "publish": "true"
        },
      ],
      "posts": [
        {
          "id": "cjoy6mxbm011k0759uaito9hs",
          "publish": true
        },
        {
          "id": "cjoy3qcsj010807595jbtqt35",
          "publish": "true"
        },
        ]
    }
  }
}
```
when just rename the ``posts`` without an additional ``posts`` field，the renamed field just return null, not []:
```
query {
  user(id: "cjqvom8dt0014088577nx1li9") {
    id
    postsNotPublished: posts(where: {publish: false}) {
        id
      	publish
    }
  }
}
```
```
{
  "data": {
    "user": {
      "id": "cjqvom8dt0014088577nx1li9",
      "postsNotPublished": null
    }
  }
}
```
The expected result should like this:
```
query {
  user(id: "cjqvom8dt0014088577nx1li9") {
    id
    posts(where: {publish: false}) {
        id
      	pubish
    }
  }
}
```
```
{
  "data": {
    "user": {
      "id": "cjqvom8dt0014088577nx1li9",
      "posts": []
    }
  }
}
```

**Comment by pantharshit00** [comment]
cc @maticzav

**Comment by pantharshit00** [comment]
@baby1990 This problem is related to prisma-bindings and it is kinda expected when you use schema delegation. You can solve this by using prisma client instead of prisma. I also think there will be no immediate solution in bindings as this is how we delegate schema

## Explanation

![image](https://user-images.githubusercontent.com/22195362/51616697-a524ae00-1f50-11e9-9333-0b127715ecd2.png)

We send the renamed field via delegation to prisma and prisma responds with the renamed thing in response which at last results in null because we expect it to be returned as a post. Prisma Client doesn't have this limitation and this is one of the reasons why we recommend client over bindings.
