### ISSUE TITLE
[mongo] upserts on embedded types

### ISSUE THREAD

**Issue by jvice152** [prisma/prisma1#3885]
**Is your feature request related to a problem? Please describe.**

referencing this https://github.com/prisma/prisma/issues/1889, I am wondering why the decision was made to exclude upserts on embeddable types.

Thanks!

**Comment by pantharshit00** [comment]
cc @do4gr

**Comment by do4gr** [comment]
The `upsert` was not enabled for lists for the example you referred to because there is currently no way to guarantee a unique value on a field in an embedded type in Mongo. Unfortunately a unique value is the necessary differentiator for our upsert mutation on toMany relations.

 There is an open bug report that unique constraints can be defined on fields of embedded types, but they are not enforced by the MongoDB engine. We therefore decided to not offer the possibility to define unique constraints in the Prisma data model on embedded types until this is fixed. 

Once this is fixed we'll enable the possibility to define uniques and unlock upsert. But the bug report has been open for a while already. https://jira.mongodb.org/browse/SERVER-1068
