### ISSUE TITLE
Generated schema/models do not have [relay] relationship connections

### ISSUE THREAD

**Issue by chrisui** [prisma/prisma1#4134]
**Describe the bug**

Generated schema/models do not have [relay] connections for relationships between types. Only root level (on `Query`) connections are made available.

**To Reproduce**

See here: https://github.com/chrisui/prisma-connections

```
type User {
  id: ID! @unique
  posts: [Post!]!
}

type Post {
  id: ID! @unique
  author: User!
}
```

**Expected behavior**

I would expect to have a `postsConnection` on `User`.

**Versions (please complete the following information):**
 - Connector: `postgres:10.3`
 - Prisma Server: `prismagraphql/prisma:1.27`
 - `prisma` CLI: `prisma v1.27.4` `node v8.11.3`
 - OS: `Windows 10`
 - other dependencies: `prisma-client`, `prisma-binding`, etc. if applicable

**Additional context**

Originally raised here: https://github.com/prisma/prisma/issues/3629#issuecomment-468024433

**Comment by pantharshit00** [comment]
Hi @chrisui 

I think this is expected behaviour. You have a posts field on your user type which you can paginate using before, after and skip.

If you want to aggregate something you filter the postsConnection by the user.

If you have any solid use case for this, we can treat this issue as a feature request.

**Comment by chrisui** [comment]
With the current setup you would require two requests to achieve the following if i'm correct. One to get users, two to filter posts by users.

```
{
  users {
    postsConnection {
      total
    }
  }
}
```

**Comment by HurricaneJames** [comment]
I do not think this is necessarily expected behavior for GraphQL connections, and it loses some of the power of GraphQL not to have connections on objects.

For example,

```graphql
query {
    user {
        playlists {
            songs {
                id
                name
            }
        }
    }
}
```

defined by

```graphql
type User {
    id: ID! @unique
    playlists: [Playlist!]!
}

type Playlist {
    id: ID! @unique
    songs: [Song!]!
}

type Song {
    id: ID! @unique
    name: String!
}
```

This is fine for a small number of playlists and songs. However, any real app is going to want connections for both Playlist and Song as they could be quite numerous.

Ideally, there would be some way to specify that playlists and songs should return the connections in the data model.

```graphql
type User {
    playlists: UserSongConnection!
}

# or with an @connection directive
type Playlist {
    songs: [Song!]! @connection
}
```

Right now, the API layer needs to implement a bunch of custom logic for each connection that could have been generated. It also makes n+1 queries from one microservice to another, and another n+1 queries from the datamodel layer to the database, incuring all the network overhead for each of those queries.

```
// first, we need to get the connection of playlists
const playlists = query(`{
    playlistsConnection(where: {user: {id: $userID}}) {
        pageInfo { ... }
        edges {
            cursor
            node { id }
        }
    }
});

// then we need to get a connection for the songs on each playlist
for (const playlist of playlists) {
    playlist.songs = query(`{
        songsConnection(where: {playlist: {id: playlist.node.id}}) {
            pageInfo { ... }
            edges {
                cursor
                node { name }
            }
        }
    });
}

// please pardon the pseudo script
```

If this was pushed to the server layer it could be optimized to a couple of DB calls.
