### ISSUE TITLE
Mongo connector leaks connections

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma1#4165]
**Describe the bug**
MongoDB connector opens connection when under load but does not release them

**To Reproduce**
https://github.com/divyenduz/prisma-4165

**Expected behavior**
MongoDB should release unused connections

**Screenshots**
MongoDB Atlast connection dashboard

<img width="511" alt="CleanShot 2019-03-11 at 15 59 57@2x" src="https://user-images.githubusercontent.com/746482/54133786-f7ddfa80-4416-11e9-874b-08415146fe5c.png">

**Versions (please complete the following information):**
 - Connector: `MongoDB`
 - Prisma Server: `1.26.5` - Not tested on latest yet because https://github.com/prisma/prisma/issues/4151
 - `prisma` CLI: `prisma/1.28.2 (darwin-x64) node-v10.4.0`

**Comment by do4gr** [comment]
The MongoDB connector is configured by providing the connection string uri. This allows you to also set its connection pooling behaviour. 

Atlas provides you with a string that does not explicitly configure the connection pooling: 
`mongodb+srv://user:pass@db.mongodb.net/test?retryWrites=true`

The MongoClient instantiated by Prisma then falls back to the defaults, a pool size of 100 and no timeout for the connections. 

If you want different behaviour, you can attach options to your uri, see here https://docs.mongodb.com/manual/reference/connection-string/#urioption.connectTimeoutMS

The following string limits the MongoClient to 10 connections and forces a connection close after 60s.  
`mongodb+srv://user:pass@db.mongodb.net/test?retryWrites=true&maxIdleTimeMS=60000&maxPoolSize=10'
`

Prisma will instantiate a client for Deploys and one for API calls, so you might see up to 20 connections here from Prisma if you mix a lot of deploys and normal queries/mutations. 

<img width="981" alt="Bildschirmfoto 2019-03-11 um 18 09 16" src="https://user-images.githubusercontent.com/16278407/54142847-dc7beb00-4428-11e9-971b-398785c0fd7f.png">

This shows the connection behaviour with default options (the first two plateaus), where Prisma will open a lot of connections and not close them (I manually shut down the Prisma container for the drops).

The later smaller peaks show the behaviour with the second connection string. Prisma will start fewer connections and close them after 60s of idle time.

**Comment by soqt** [comment]
I have a problem with every new connection takes too much time(a couple seconds from server), then the client can perform queries or mutations very fast. And after certain time users need to wait the same time to reconnect to mongoDB. Is this the same problem?

**Comment by do4gr** [comment]
Hey @soqt, I think this is a different issue. 

So this `com.mongodb.MongoSocketException: mongo: System error` indicates a networking related issue. See:  https://mongodb.github.io/mongo-java-driver/3.6/javadoc/com/mongodb/MongoSocketException.html

Since Prisma is able to pick up the connection I suspect that that is not a Prisma issue but that the network connection between Prisma and Mongo is somehow unstable. 

You can of course also try to play around with the connection string settings for Mongo and see if that helps. See here: https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options

`socketTimeoutMS` and `connectTimeoutMS` are related to the connection.
