### ISSUE TITLE
Failed migration hammered database

### ISSUE THREAD

**Issue by jhalborg** [prisma/prisma1#4207]
**Describe the bug**
A schema migration on our production server failed for unknown reasons, perhaps due to too much load on our instance and hence a timeout. I tried `prisma deploy` again, got the same schema change ouput, and another timeout. 

I then went to inspect the logs for my server, which repeatedly printed out fatal failures with connection timeouts to the database (5sec+), citing `Too many connections`, which is an Amazon Aurora cluster. I then went to inspect the cluster, and it was under 100% load. 

I tried restaring the Prisma server, no effect. I then restarted the Aurora cluster, but the Prisma server kept failing. When I then restarted the cluster again, it booted successfully. 

I suspect the issue was that the migration script kept retrying after it failed, leading to it dominating the connection pool and flooring the DB. 

**To Reproduce**
Not sure - produce a timeout on a migration somehow. 

**Expected behavior**
For the migration script to back off, perhaps have a "stop migration" mutation in the management API

**Versions (please complete the following information):**
 - Connector: `MySQL`
 - Prisma Server:`1.23.4`
 - `prisma` CLI: `prisma/1.21.1`
 - OS: `OS X Mohave`

**Additional context**
Inspecting the management API, it lists two rollbacks and a success - but the changes were never applied, the old schema is still active when accessing the Prisma project. 

```
{
  # migrationStatus(name:"projectname", stage:"prod"){
  listMigrations(name: "brandheroes-backend", stage: "prod") {
    projectId
    status
    applied
    startedAt
    finishedAt
  }
  serverInfo{
    version
  }
}
```

produces

```
{
  "data": {
    "listMigrations": [
      {
        "applied": 30,
        "projectId": "__THEID__",
        "status": "SUCCESS",
        "startedAt": "2019-03-18T13:48:54.000Z",
        "finishedAt": "2019-03-18T13:48:55.000Z"
      },
      {
        "applied": 26,
        "projectId": "__THEID__",
        "status": "ROLLBACK_SUCCESS",
        "startedAt": "2019-03-18T13:24:21.000Z",
        "finishedAt": "2019-03-18T13:25:31.000Z"
      },
      {
        "applied": 26,
        "projectId": "__THEID__",
        "status": "ROLLBACK_SUCCESS",
        "startedAt": "2019-03-18T13:21:38.000Z",
        "finishedAt": "2019-03-18T13:22:49.000Z"
      },
      {
        "applied": 41,
        "projectId": "__THEID__",
        "status": "SUCCESS",
        "startedAt": "2019-02-28T15:11:35.000Z",
        "finishedAt": "2019-02-28T15:11:39.000Z"
      },
      ...
    ],
    "serverInfo": {
      "version": "1.23.4"
    }
  }
}
```

**Comment by pantharshit00** [comment]
For these cases, mostly I fix them by deleting the last migration from the database and trying again. I will be hard to fix as the reproduction of the problem is not very easy.

I think we can treat this issue as an FR for stop migration mutation in the management API although the migration system will be quite different in the near future as there will be no prisma server(see https://github.com/prisma/rfcs/blob/migrations/text/0000-migrations.md).

**Comment by jhalborg** [comment]
@pantharshit00 - Thanks 👍 A couple of questions:

> deleting the last migration from the database

How would I go about that on a managed solution like Aurora? To my knowledge, and after a quick google search, there's no way to do that directly on the database server. Furthermore, I'm pretty confident that it was the Prisma server that tried to apply the migration in a loop, not the DB server itself, but have no way to verify this theory. 

But sure, it makes sense to treat this issue as a FR for a `migrationStop` mutation. 

`in the near future as there will be no prisma server` - Didn't know this was a thing, but I do see it [on the roadmap](https://github.com/prisma/prisma/blob/master/ROADMAP.md). Will this be the preferred/recommended setup going forward, or is it just to make it easier to onboard new users?

**Comment by pantharshit00** [comment]
> How would I go about that on a managed solution like Aurora?

I believe you can connect to it using any MySQL client. See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Connecting.html. I personally use tableplus.io for these tasks.

> in the near future as there will be no prisma server - Didn't know this was a thing, but I do see it on the roadmap. Will this be the preferred/recommended setup going forward, or is it just to make it easier to onboard new users?

Yes, it is meant to onboard new users and make prisma easy to use. It will be performant as well.  But Prisma server is also in works and it right now being written in rust so that we can eliminate JVM as a dependency (you know about the memory situation I guess). It will be there for larger applications where using its capabilities can largely impact performance.
