### ISSUE TITLE
Prisma 2

### ISSUE THREAD

**Issue by schickling** [prisma/prisma1#4256]
# Overview

Read more about the Prisma 2 preview here: https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5

# RFCs

- **Migrations**: [RFC](https://github.com/prisma/rfcs/blob/migrations2/text/0000-migrations.md) / [Discussion](https://github.com/prisma/rfcs/pull/10)
- **Datamodel**: [RFC](https://github.com/prisma/rfcs/blob/datamodel/text/0000-datamodel.md) / [Discussion](https://github.com/prisma/rfcs/pull/11)
- **JavaScript/TypeScript Client API**: [RFC](https://github.com/prisma/rfcs/blob/new-ts-client-rfc/text/0000-new-ts-client.md) / [Discussion](https://github.com/prisma/rfcs/pull/2)
- **Client generators**: [RFC](https://github.com/prisma/rfcs/blob/client-generators/text/0000-client-generators.md) / [Discussion](https://github.com/prisma/rfcs/pull/4)
- **Unit of work**: [RFC](https://github.com/prisma/rfcs/blob/unit-of-work/text/0000-unit-of-work.md) / [Discussion](https://github.com/prisma/rfcs/pull/5)
- **Go Client API** [RFC](https://github.com/prisma/rfcs/blob/photon-go-api/text/0000-prisma-client-go.md)
- **Engine/Connector Architecture** 
- **Configuration**
- **Import/Export**
- **CLI**
- **Seeding**
- **SDK**

# Repositories

https://github.com/prisma/prisma2
https://github.com/prisma/prisma2-cli
https://github.com/prisma/photonjs
https://github.com/prisma/lift
https://github.com/prisma/prisma2-docs

**Comment by brillout** [comment]
This all sounds exciting :+1:. Any ETA for a Prisma 2 beta/alpha release?

**Comment by edunomatseye** [comment]
Pls let me know when we can use prisma with using Docker. That would be the greatest update I would love to see.

**Comment by outerlook** [comment]
Hi! Will I have to do any changes to my Nexus-prisma integration?

**Comment by pantharshit00** [comment]
We have released the preview of Prisma 2.

Read the announcement post here: https://www.prisma.io/blog/announcing-prisma-2-zq1s745db8i5

We would love to hear your thoughts on this.

**Comment by mk0a1a** [comment]
Any ETA on Go client API?

**Comment by marcus-sa** [comment]
Any chance that there'll be a configuration for the CLI? Currently it just generates the Photon ORM in a `@generated/*` directory inside `node_modules`.
This won't work if you by any chance are using microservices or several servers in the same monopoly repository as the generated path can't be specified since they'll just override each other.

**Comment by pantharshit00** [comment]
@marcus-sa 

You can configure an output property in the generator block now.

```grovvy
generator photon {
	provider = "photonjs"
    output = "./generated/photon"
}
```

**Comment by ntziolis** [comment]
One of the top reasons to use prisma is ability to easily leverage subscriptions from the DB layer without having to worry about it. Since you are moving the prisma engine side by side with the app:

How are subscriptions handled in a multi instances scenario?
- Subscription open for inserts of TypeA on Instance 1
- Record inserted for TypeA on Instance 2

How will Instance 1 know about the insert? Is there a way to "link" the prisma engines across instances?

**Comment by pantharshit00** [comment]
@ntziolis 

Right now Prisma 2 doesn't ship with a subscriptions solutions yet. We have a plan for an events engine which will be bin-log based rather than using the data which we have in the Prisma 2 which will be more sustainable. I can't give you an ETA on that as we are willing to spend time on designing the engine carefully.

**Comment by ntziolis** [comment]
@pantharshit00 Thank you for this info. Please keep us informed on progress here as without DB subscriptions we do not have much use for prisma tbh.

**Comment by hoffnung8493** [comment]
I am considering to use prisma in production, but not sure if I should use prisma 1 or prisma 2. In terms of stability it makes sense to use prisma 1, but because of the docker part, I would rather use prisma 2. I only need stable graphql `query` and `mutation` to work(no `subscription` for now). Can you guys share some advice on this issue?

**Comment by bmcilw1** [comment]
@hoffnung8493 I am in the same boat trying the decide the same. I am designing the backend for a startup. I love the ease of development with Prisma. However, it must be deployed to production, and when it does it needs to work. However, our use case is overall very simple and minimal from a load perspective. 

## Background
- Our app will not be ready for full production deployment for 2-3 months, so both projects have about that long to progress.
- We've used a serverless GraphQL backend to maximize flexibility and minimize boilerplate on our front end while preparing us for scale.
- The nature of our data is that it is highly partitionable per user. It can fit in a relational database, but the more ideal database for it is certainly Mongo due to the partionability and higher availability. Because of Prisma's Import/Export functionality, we may be able to initially deploy to a relational DB until Mongo support comes to v2, at which point, we'd export our data and import it into Mongo.
- Expected usage of the app would be intermittent. Most users would only need to use the app for 1-6 weeks and not again for as much as a decade. Because of this, metrics like max concurrent users as well as the load-per-user metrics would be minimal. It shouldn't be hard to scale to 1,000s and 10,000s of users as only perhaps 10% of that would be actively accessing data at a given time.
- Currently, there is no need for real-time data flow via subscriptions.

Would Prisma 2 (v2) likely be just good enough to handle this simple workflow? If not, is Prisma 1 (v1) able to handle this stably and in prod? If we must use v1, is there a way we can make a Prisma server capable of handling a maximum of 100s of concurrent users that could be done in a day or 2? Is there any way that doesn't require a Docker/Kubernetes distributed DevOps expert or me becoming one in order to get this thing deployed?

Thoughts?

**Comment by pantharshit00** [comment]
Hi all,

I am going to lock this issue now as the feedback is getting fragmented among repositories for us. Please open a new issue here if you want to ask about something: https://github.com/prisma/prisma2. I am going to answer the last remaining questions here:

Right now we are also in a weird state ourselves on whether to recommend a new user Prisma 1 or Prisma 2. Right now I will say don't use Prisma 2 for a very large application as we may have breaking changes over a period of a week and it is not very stable. For a side project, it has enough query capabilities right now as you can see in Matt's talk here: https://www.youtube.com/watch?v=WSyaBOAZFZY. So I will recommend you to all to use Prisma 1 for your current large projects and adopt Prisma 2 after it has become stable enough for production usage. For any other project, it will be great if you can test out Prisma 2 and give us your valuable feedback.

For performance and scalability issues, they were one of the reasons why we wrote Prisma 2 in Rust and we now support serverless environments as well so you will need not to be a DevOps expert. Prisma 2 is just a library, scale it like any other node app. So you will need to migrate to Prisma 2 here. So for existing Prisma 1 users, please wait till general release and migrate your application to Prisma 2. 

Any new user that is willing to use prisma for a small project should use Prisma 2. Any other user that is trying to write a large application should use Prisma 1 and incrementally adopt Prisma 2 after the general release. 

Also, we will continue to do bug fixes in Prisma 1 and new issues will get addressed. Just no new feature will be released though.

**Comment by steebchen** [comment]
@mk0a1a For the Prisma 2 Go client, please see the tracking issue https://github.com/prisma/prisma2/issues/571 and the actual work at https://github.com/prisma/photongo.
