### ISSUE TITLE
Prisma init on existing mysql database fails during introspection

### ISSUE THREAD

**Issue by vlad-blana** [prisma/prisma1#4551]
**Describe the bug**
Calling prisma init on existing database generates an error: "TypeError: cannot read property 'type' of undefined"

**To Reproduce**
1. Use windows 10 x64 and install node.js 12.2.0 or 10.15.3
2. Use the command line to install the npm package prisma v1.33.0
3. Import the attached mysql schema in a mysql 5.7 server
4. Run prisma init in the command line
- select Use Existing Database
- select Mysql
- select Yes for "Does your database contain existing data?"
- enter your mysql credentials - ex: localhost, port 3306, user, password
- select the mysql database/schema that you've imported for introspection
- wait a bit and it will give you the "TypeError: cannot read property 'type' of undefined"

**Expected behavior**
There should be no error, and the next step in the wizard (generation option) should appear and in the end the prisma.yml, schema.prisma and generated folders and its content (depending on the generator selection: ts, js, ... , none) should appear in the directory the prisma init command is run.

**Screenshots**
See attached image showing the error and the callstack - I've used set DEBUG=* & prisma init for it.

**Versions (please complete the following information):**
- MySQL Server 5.7.26
- Prisma 1.33 CLI on node 12.2.0
- OS: Windows 10 Pro x64

**Additional context**
![image_2019_05_15T13_17_16_636Z](https://user-images.githubusercontent.com/42930668/57853208-cc4c0780-77ed-11e9-9817-d6f9ad0454b4.png)
[schema_to_test_prisma1.33_introspection.zip](https://github.com/prisma/prisma/files/3186992/schema_to_test_prisma1.33_introspection.zip)

**Comment by cullophid** [comment]
I have the same issue

**Comment by 0x15f** [comment]
I'm having this issue as well. Using MariaDB.

**Comment by 0x15f** [comment]
Possibly related to https://github.com/prisma/prisma/issues/3979 ?

**Comment by dougwhite** [comment]
Hi all, I had this problem also but in a different place. I started putting together a PR but I couldn't even get prisma to build... I'm leaving this so hopefully somebody smarter than me can fix it.

The cause is related to the mysql information_schema column names being UPPERCASE by default in windows. While case sensitivity is ignored when querying the information_schema, the typescript object returned by .query() still contains an UPPERCASE property name. The code however assumes that the field will be returned as lowercase.

[relationalConnector.ts:80](https://github.com/prisma/prisma/blob/298be5c919119847bb8d102d6b16672edd06b2c5/cli/packages/prisma-db-introspection/src/databases/relational/relationalConnector.ts#L80)
```ts
public async listSchemas(): Promise<string[]> {
    const res = await this.query(
      `SELECT 
         schema_name       // <-------- on windows this column is uppercase : SCHEMA_NAME
       FROM 
         information_schema.schemata
       WHERE schema_name NOT LIKE 'information_schema';`,
    )

    return res.map(x => x.schema_name)       //   <----------- x == { SCHEMA_NAME: "mydatabase" }
  }
```

I was able edit the .js file here:   
`%\AppData\Roaming\npm\node_modules\prisma\node_modules\prisma-db-introspection\dist\databases\relational\relationalConnector.js`

Changing the return to `x.SCHEMA_NAME` fixed my issue and I was able to generate a schema correctly.
However this would just break linux clients, so perhaps a better fix is: `x[0]` since the query should return only 1 column.

In regards to @vlad-blana and @0x15f experiencing similar problems, their stack trace points to [relationalIntrospectionResult.ts:348](https://github.com/prisma/prisma/blob/298be5c919119847bb8d102d6b16672edd06b2c5/cli/packages/prisma-db-introspection/src/databases/relational/relationalIntrospectionResult.ts#L348)

I believe somewhere up the chain you will find a similar assumption about lowercase / uppercase being made, which is filling the types array with undefineds.

Hope that is of some use to people.
