### ISSUE TITLE
Must I write resolvers?

### ISSUE THREAD

**Issue by gotexis** [prisma/prisma1#4694]
Hey, A total noob here looking to develop my first GraphQL server. So this is probably a noob question, but definitely not a troll question cause I do need help

My stack is Prisma + apollo-server 2, and my server look like this:

```js
export default new ApolloServer({
    typeDefs: parse(typeDefs),  // generated by prisma, OK
    // resolvers: ???? should be some default resolvers even if i don't provide my own?
    context: req => ({
        ...req,
        db: prisma,
    })
})
```

Problem is, you see, I don't have a resolver.

But I noticed I can still execute a query for a single item like this:
```graphql
{
  user(where:{id: "someID"}) {
    id
    name
    email
    password
  }
}
```

But when I try to do a `ListQuery`, the query never runs:

```gql
{
  users(first:3}) {
    id
    name
    email
    password
  }
}
```

the error is:
`Cannot return null for non-nullable field for field Query.users.`

Is this due to the lack of resolver, or something else? Thanks in advance.

**Comment by pantharshit00** [comment]
You will definitely need to implement resolvers. Otherwise, GraphQL will be unable to resolve any subtypes like users.

Here is a blog post on common resolver patterns with Prisma:https://www.prisma.io/tutorials/a-guide-to-common-resolver-patterns-ct08/

You can also see this example authentication app which is implemented using Prisma: https://www.prisma.io/tutorials/authentication-in-apollo-server-ct21/
