### ISSUE TITLE
Prisma in unable handle enums when no migrations is enabled

### ISSUE THREAD

**Issue by pantharshit00** [prisma/prisma1#4715]
**Describe the bug**
Prisma is throwing an error when Enum is used with no migrate flag.

**To Reproduce**
1. Deploy the following datamodel with Prisma deploy
```graphql
enum test {
  ADMIN
  USER
}

type User {
  id: ID! @id
  name: test!
}
```
3. Deploy the same datamodel again with `--no-migrate` flag

**Expected behaviour**
Prisma should be able to deploy enum type if underlying type is a string.

**Screenshots**
![image](https://user-images.githubusercontent.com/22195362/60605149-97643600-9dd6-11e9-91f0-4f5e208b3810.png)

**Versions (please complete the following information):**
 - Connector: Postgres
 - Prisma Server: 1.34.0
 - `prisma` CLI: Prisma CLI version: prisma/1.34.0 (darwin-x64) node-v10.16.0
 - OS: MacOS 10.14.5 Mojave

**Comment by iyeremuk** [comment]
Having the same issue after upgrading to 1.34.0.

**Comment by brafdlog** [comment]
Same issue.

**Comment by blazestudios23** [comment]
I'm having the same issue when deploying to an existing schema with 1.34.5, I get the following error message:
`
java.lang.RuntimeException: Encountered unknown SQL type enum with column content_type.
`

**Comment by blazestudios23** [comment]
I did a test where I built an enum in an stand alone Prisma container that has full control of the DB and found that instead of creating a MySQL enum(), Prisma just creates a varchar. 

My existing DB uses enum()s and that's not going to change, I think that it's better to use the built in MySQL enum() rather than a varchar and then putting the logic in Prisma, if you stop using Prisma and switch to a different service it's better to have the enum stored in the database. Or if you have other services interacting with the same DB, it's important to use the MySQL build in enum(), we have a massive data pipeline and databases are used by a few different services.
