### ISSUE TITLE
[Discussion] Streamlining Prisma's support channels

### ISSUE THREAD

**Issue by nikolasburk** [prisma/prisma1#4829]
Hey everyone 👋 we want to use this GitHub issue to spark a discussion about the variety of Prisma's community and support channels and how to organize them better. Please leave your feedback and ideas!

We currently have the following official and unofficial community and support channels:

- Slack
- GitHub
- Prisma forum
- Spectrum
- Intercom
- Email
- Stackoverflow

Our support team is working very hard but taking care of all the channels at once is an almost impossible task. We're currently evaluating how to streamline the channels, here are a few of our thoughts.

While we currently use **Slack** as our main communication channel to the community, there are some problems Slack brings when used with a community as huge as ours (we currently have more than 18k members in our Slack). Mostly, there's no way to make Slack messages searchable on the web (e.g. via Google). This means we can't point to older replies when a question is being repeatedly asked on Slack and users don't have a good way of finding previous answers in the first place. The realtime aspect of Slack is great, but to provide sustainable support it should be possible to persist and reuse previous answers.

We use the **Prisma forum** to enable broader discussions among community members and respond to questions with our support team. These questions and answers can be persisted, but many of our users aren't aware of the forum and rather default to asking questions on Slack. Another issue is that our forum is running on discourse which requires our users to create an extra account.

**Spectrum** seemed to be a great middleground between the ability to provide realtime support and persisting conversations so that they could be reused later. Many companies have already moved their communities to Spectrum (e.g. [ZEIT](https://zeit.co/blog/spectrum) and [Apollo](https://blog.apollographql.com/goodbye-slack-hello-spectrum-8fa6b979645b)), however, we've been hesitant for a few reasons:

- We are worried about Spectrum's reliability as it has been facing regular downtimes
- Spectrum doesn't yet provide a mobile app which we consider an important factor
- The chat experience often is fairly slow

While we believe that the Spectrum team would be able to fix the above issues, we're worried that Spectrum isn't actively developed any more ([the last commits are from almost two months ago](https://github.com/withspectrum/spectrum/commits/alpha)). 

So, instead of moving our community to Spectrum, we'd rather hear your opinions and thoughts. Are you aware of a community management tool that might help or have other feedback to share? Please let us know your ideas!

**Comment by gustawdaniel** [comment]
Is there any place when voting on features priorities is possible?

I think github issues for bugs and features + stackoverflow for valuable questions + slack / forum for community + blog for news and plans announcing is great composition. I do not have opinion about Spectrum.

**Comment by uinvent** [comment]
My team is going to build a software product with graphQL and selected Prisma for this. 
Our first customer release will be in next 3-4 months; Now I need to know that should I go for Prisma 2 or Prisma 1.3+ ?

**Comment by denkristoffer** [comment]
I understand the reasons you mention for not going to Spectrum, (worth mentioning that [development seems to be active again](https://github.com/withspectrum/spectrum/commits/alpha), though) but the fact that Slack hides old conversations is really a big, big hindrance and is, in my opinion, reason enough to move away.

Hopefully Spectrum will revive its mobile client.

**Comment by ben-siewert** [comment]
**Struggling to get graphql-yoga to work with prisma and docker**

I used this as a starting point:
https://github.com/howtographql/react-urql

I followed the docker instructions and it works locally.

However, if I add a service for the graphql-yoga server, I get a "connection refused" error when I go to the playground to test. The graphql-yoga server works but won't connect to the prisma layer as the connection is refused.

**Comment by robertcoopercode** [comment]
@nikolasburk I've tried to join the slack community, but it seems like the invite page is broken: https://slack.prisma.io/invite

It's been like this for a while since I tried about 2 weeks ago as well. I tried [pinging Prisma on Twitter](https://twitter.com/RobertCooper_RC/status/1203823661423169536), but got no response.

Any help would be appreciated.

**Comment by MJGTwo** [comment]
Bumping this. The invite link is still broken.

**Comment by gDelgado14** [comment]
@MJGTwo the link is located at https://slack.prisma.io/

**Comment by gDelgado14** [comment]
> We use the Prisma forum to enable broader discussions among community members and respond to questions with our support team

What do you mean? The forum is closed and is in read-only mode.

Also, the slack channel has almost 30,000 people yet questions on the #general channel don't seem to get any response.

--- 

Could you maybe provide a set of criteria that you and your team are using to assess the viability / appropriateness of a platform? That would help the community provide you better answers to what you're looking for. 

From "reading between the lines", you want:

- Searcheable / indexable content 
- Platform is in active maintenance

What else?

From the above 2 criteria, I do think that slack being a closed system isn't a good candidate, which is why I think making stack overflow the de-facto forum might be the right direction. I'm not familiar with discourse, but it seems like it's achieving the same goal as Slack. Same thing with spectrum - seems like it does the same thing as SO, except it's not as well-maintained as SO.

Github could be used in tandem with SO for bug reports and feature requests.
